export default  {
    products:[
        {
            _id:'1',
            name:'choco donut',
            category: 'sweets',
            image:'/img/product-9.png',
            price:18,
            brand:'Fantasy',
            rating:'★★★★✰',
            
            numReviews: 7,
            countInStock:5,
            description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
        },
        {
            _id:'2',
            name:'flavouer',
            category: 'sweets',
            image:'/img/product-10.png',
            price:14,
            brand:'ibaco',
            rating:'★★★✰✰',
            
            numReviews: 7,
            countInStock:2,
            description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
        },
        {
            _id:'3',
            name:'dark forest',
            category: 'cakes',
            image:'/img/product-11.png',
            price:75,
            brand:'Cookers',
            rating:'★★★★★',
            
            numReviews: 7,
            countInStock:6,
            description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
        },
        {
            _id:'4',
            name:' sugar puffs',
            category: 'sweets',
            image:'/img/product-12.png',
            price:20,
            brand:'Fantasy Bakers',
            rating:'★★★★★',
            
            numReviews: 7,
            countInStock:3,
            description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
        },
        
    {
        _id:'5',
        name:'rasgulla',
        category: 'sweets',
        image:'/img/product-5.png',
        price:26,
        brand:'ibaco',
        rating:'★★★✰✰',
        
        numReviews: 7,
        countInStock:6,
        description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
    },
    {
        _id:'6',
        name:'jelabi',
        category: 'sweets',
        image:'/img/product-6.png',
        price:15,
        brand:'bake-joy',
        rating:'★★★★✰',
        
        numReviews: 7,
        countInStock:10,
        description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
    },
    {
        _id:'7',
        name:'plum cake',
        category: 'cakes',
        image:'/img/product-7.png',
        price:30,
        brand:'Fantasy Bakers',
        rating:'★★✰✰✰',
        
        numReviews: 7,
        countInStock:3,
        description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
    },
    {
        _id:'8',
        name:'khaju doodh',
        category: 'sweets',
        image:'/img/product-8.png',
        price:25,
        brand:'Bitte store',
        rating:'★★★★✰',
        
        numReviews: 7,
        countInStock:7,
        description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
    },
    {
        _id:'9',
        name:'Cake',
        category: 'cakes',
        image:'/img/product-1.png',
        price:45,
        brand:'Elite Cakes',
        rating:'★★★★★',
      
        numReviews: 10,
        countInStock:4,
        description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
    },
    {
        _id:'10',
        name:'Buns',
        category: 'cakes',
        image:'/img/product-2.png',
        price:25,
        brand:'Elite Cakes',
        rating:'★★★★✰',
        
        numReviews: 10,
        countInStock:6,
        description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
    },
    {
        _id:'11',
        name:'Ladoos',
        category: 'sweets',
        image:'/img/product-3.png',
        price:30,
        brand:'Elite Cakes',
        rating:'★★★✰✰',
        
        numReviews: 10,
        countInStock:3,
        description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
    },
    {
        _id:'12',
        name:'cookies',
        category: 'sweets',
        image:'/img/product-4.png',
        price:12,
        brand:'Fantasy Bakers',
        rating:'★★★★✰',
        
        numReviews: 7,
        countInStock:6,
        description: 'hello we are selling our products like hot cakes do take them and have a chance to taste the limited offer cakes to get new experience by grabing ur treats for your frends and family come on quick place the order soon before it gets over ',
    },

]
}